import { createClient } from "@/lib/supabase/server";
import CaptionsViewer from "./CaptionsViewer";

export const revalidate = 0;

export default async function CaptionsPage() {
  const supabase = await createClient();

  const [{ data: flavors }, { data: captions }, { data: allIds }] = await Promise.all([
    supabase
      .from("humor_flavors")
      .select("id, slug")
      .order("slug"),
    supabase
      .from("captions")
      .select("id, image_id, content, humor_flavor_id, created_datetime_utc")
      .order("created_datetime_utc", { ascending: false })
      .limit(200),
    supabase
      .from("captions")
      .select("humor_flavor_id")
      .not("humor_flavor_id", "is", null),
  ]);

  // Build accurate per-flavor counts from full dataset
  const flavorCounts: Record<number, number> = {};
  for (const row of allIds ?? []) {
    const fid = row.humor_flavor_id as number;
    flavorCounts[fid] = (flavorCounts[fid] ?? 0) + 1;
  }

  return (
    <div className="p-8 max-w-5xl mx-auto">
      <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Captions</h1>
      <p className="text-gray-500 dark:text-gray-400 mb-6">
        Browse captions generated by each humor flavor. Use the filter to narrow by flavor.
      </p>

      <CaptionsViewer
        flavors={flavors ?? []}
        captions={captions ?? []}
        flavorCounts={flavorCounts}
        totalCount={allIds?.length ?? 0}
      />
    </div>
  );
}
