import { createClient } from "@/lib/supabase/server";
import CaptionsViewer from "./CaptionsViewer";

export const revalidate = 0;

export default async function CaptionsPage() {
  const supabase = await createClient();

  // Fetch flavors, recent captions, and total count in parallel
  const [{ data: flavors }, { data: captions }, { count: totalCount }] = await Promise.all([
    supabase.from("humor_flavors").select("id, slug").order("slug"),
    supabase
      .from("captions")
      .select("id, image_id, content, humor_flavor_id, created_datetime_utc")
      .order("created_datetime_utc", { ascending: false })
      .limit(200),
    supabase.from("captions").select("*", { count: "exact", head: true }),
  ]);

  // Get accurate per-flavor counts via parallel HEAD queries (no row data returned)
  const flavorList = flavors ?? [];
  const countPairs = await Promise.all(
    flavorList.map(async (f) => {
      const { count } = await supabase
        .from("captions")
        .select("*", { count: "exact", head: true })
        .eq("humor_flavor_id", f.id);
      return [f.id, count ?? 0] as [number, number];
    })
  );
  const flavorCounts = Object.fromEntries(countPairs);

  return (
    <div className="p-8 max-w-5xl mx-auto">
      <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Captions</h1>
      <p className="text-gray-500 dark:text-gray-400 mb-6">
        Browse captions generated by each humor flavor. Use the filter to narrow by flavor.
      </p>

      <CaptionsViewer
        flavors={flavorList}
        captions={captions ?? []}
        flavorCounts={flavorCounts}
        totalCount={totalCount ?? 0}
      />
    </div>
  );
}
