import { createClient } from "@/lib/supabase/server";
import CaptionsViewer from "./CaptionsViewer";

export const revalidate = 0;

export default async function CaptionsPage() {
  const supabase = await createClient();

  const [{ data: flavors }, { data: captions }] = await Promise.all([
    supabase
      .from("humor_flavors")
      .select("id, slug")
      .order("slug"),
    supabase
      .from("captions")
      .select("id, image_id, caption_text, humor_flavor_id, created_at")
      .order("created_at", { ascending: false })
      .limit(200),
  ]);

  return (
    <div className="p-8 max-w-5xl mx-auto">
      <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Captions</h1>
      <p className="text-gray-500 dark:text-gray-400 mb-6">
        Browse captions generated by each humor flavor. Use the filter to narrow by flavor.
      </p>

      <CaptionsViewer
        flavors={flavors ?? []}
        captions={captions ?? []}
      />
    </div>
  );
}
